config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :users do 
    resources :years
  end
  resources :hospitals

  resources :years do
    resources :comments, module: :years
    resources :months do
    resources :comments, module: :months      
      resources :days do
        resources :comments, module: :days
        resources :sugar_levels
        resources :meals
        resources :exercises
        resources :warnings
        resources :insulin_injections
      end
    end
  end

  get "add_day", to: "days#add_day" 
  get "/users/add_patient/:id", to: "users#add_patient"
  get "/users/accept_request/:id", to: "users#accept_request"
  get "/users/add_to_hospital/:id", to: "hospitals#add_to_hospital"
  get "/users/accept_hospital/:id", to: "hospitals#accept_hospital"
  get "/users/deny_hospital", to: "hospitals#deny_hospital"
  get "/personal_page", to: "users#personal_page"
  get "/predict_bsl/day_:id", to: "days#predict_blood_sugar_level"

  root "years#index"
end

app/models/month.rb
class Month < ApplicationRecord
  belongs_to :user
  belongs_to :year
  has_many :days, dependent: :destroy
  has_many :comments, as: :commentable
  before_save :change_created_at

  def change_created_at
  	self[:created_at] = "#{year.created_at.year}-#{Date::MONTHNAMES.index(self.month_name).to_i}-01"
  end

  def average_month
  	all_days = days.map {|day| day.average }
  	amount = all_days.count
  	unless all_days.include? nil
  	  sum = all_days.inject(0) { |sum, x| sum + x }
  	  sum / amount if amount != 0
    end
  end

end

app/controllers/months/comments_controller.rb
class Months::CommentsController < CommentsController
  before_action :set_commentable

  private

  def set_commentable
  	@commentable = Month.find(params[:month_id])
  end

end

app/controllers/months_controller.rb
class MonthsController < ApplicationController

  def create
    @year = Year.find(params[:year_id])
    if @year.months.select{|month| month.month_name == month_params[:month_name]}.empty?
      @year.months.create(month_params)
    else
      flash[:notice] = "Month already exists"
    end
    redirect_to :back
  end

  def destroy
    @year = Year.find(params[:year_id])
    @month = Month.find(params[:id])
    @month.destroy
    redirect_to year_path(@year)
  end

  def index
    @months = Month.all
  end

  def month_type
    if @month.month_name == "February"
      (1..28).to_a
    else
      (1..31).to_a
    end
  end

  def current_month?(month_name)
    @month = Month.find(params[:id])
    month_name == @month.month_name ? true : false
  end

  def calendar_months(year)
    @all_month = {}
    Date::MONTHNAMES[1..-1].each do |month_name|
      @all_month[month_name] = [false, current_month?(month_name)]
    end
    year.months.where.not(created_at: nil).each do |month|
      @all_month[month.month_name] = [true, current_month?(month.month_name)]
    end
  end

  def calendar_days(month)
    @all_days = {}
    (1..30).to_a.each do |month_day|
      @all_days[month_day] = false
    end
    @month.days.where.not(created_at: nil).each do |day|
      @all_days[day.created_at.day] = true
    end
  end

  def show
    @year = Year.find(params[:year_id])
    @month = Month.find(params[:id])
    calendar_days(@month)
    calendar_months(@year)
    @days_collection = month_type - @month.days.map(&:day_number)
    @status_hash = {}
    @sug = @month.days.map{|day| day.sugar_levels.map{|sl| sl.status }}
    @status_hash[:Low] = @sug.flatten.count("Low")
    @status_hash[:High] = @sug.flatten.count("High")
    @status_hash[:Normal] = @sug.flatten.count("Normal")
    @total = []
    @month.days.each do |day|
      mmols = day.sugar_levels.map {|e| e.mmol}
      time  = day.sugar_levels.map {|e| e.created_at}
      @total << {name: "#{day.created_at.day}", data: time.zip(mmols).to_h, type: "area"}
    end
  end

  private

  def month_params
    params.require(:month).permit(:compensation, :month_name, :year_id, :id)
  end

end

app/views/months/show.html.erb
<%= link_to "Back to year", "/years/#{@year.id}" %>
<%= line_chart @total %>
<%= pie_chart(@status_hash, adapter: "google") %>


<div class="row" style="margin-top: 8%;">	
 <div class="col-sm-4"> 
  <div class="calendar-left">

<div class="positioning" style="padding-top: 40%">
    <div class="num-date"><%= @month.created_at.year %></div>
    <div class="day"><%= @month.month_name[0..2] %></div>
    <%= button_to "Delete month", year_month_path(@year, @month), class: "btn btn-primary btn-lg btn-block login-button", style: "width: 200px; margin-left: 50px;", method: :delete, data: { confirm: "Are you sure?" } %>
</div>

  </div>
 </div>

<div class="col-sm-4">
  <div class="calendar-base">

    <div class="months">

      <% @all_month.each do |month_name, state| %>
        <% if state[0] == true %>
         <%= link_to year_month_path(@year, Month.where(created_at: "#{@year.created_at.year}-#{Date::MONTHNAMES.index(month_name).to_i}-01").first.id), style: "color: #AAAAB1" do %>

          <% if state[1] == false %>
          <span class="month-hover"><%= month_name[0..2] %></span>
          <% else %>
          <strong class="month-color"><%= month_name[0..2] %></strong>
          <% end %>

         <% end %>
        <% else %>
          <span class="month-hover"><%= month_name[0..2] %></span>  
        <% end %>
      <% end %>  
    </div><!-- months -->

    <hr class="month-line" />

    <div class="days">SUN MON TUE WED THU FRI SAT</div>
    <!-- days -->

    <div class="num-dates">

      <div class="first-week"><span class="grey">26 27 28 29 30 31</span> 
       <% if @all_days[1] == true %>
<%= link_to year_month_day_path(@year, @month, Day.where(created_at: "#{@month.created_at.year}-#{@month.created_at.month}-#{1}").first.id) do %>
<strong class="active-day">01</strong>
<% end %>
<% else %>
<%= link_to "1", add_day_path(day: {day_number: 1, year_id: @year.id, month_id: @month.id}), class: "month-day", style: "color: black", method: :get %>
<% end %>
      </div>


<%@all_days.except(1, 30).each_slice(7) do |slice|%>
<div class="first-week">
<% slice.each do |k, v| %>
<% if v == true %>
<%= link_to year_month_day_path(@year, @month, Day.where(created_at: "#{@month.created_at.year}-#{@month.created_at.month}-#{k}").first.id) do %>
<strong class="active-day"><%= k.to_s.length == 1 ? "0#{k}" : k  %></strong>
<% end %>
<% else %>
<%= link_to (k.to_s.length == 1 ? "0#{k}" : k), add_day_path(day: {day_number: k, year_id: @year.id, month_id: @month.id}), class: "month-day", style: "color: black", method: :get %>
<% end %>
<% end %>
</div>
<% end %>

      <div class="sixth-week"> 
 <% if @all_days[30] == true %>
<%= link_to year_month_day_path(@year, @month, Day.where(created_at: "#{@month.created_at.year}-#{@month.created_at.month}-#{30}").first.id) do %>
<strong class="active-day">30</strong>
<% end %>
<% else %>
<%= link_to "30", add_day_path(day: {day_number: 30, year_id: @year.id, month_id: @month.id}), class: "month-day", style: "color: black", method: :get %>
<% end %>
       <span class="grey">01 02 03 04 05 06</span></div>

    </div>
    <div class="event-indicator"></div>
    
    <div class="event-indicator two"></div>

  </div>
</div>
</div>

<%= render partial: "comments/comments", locals: {commentable: @month} %>

<div class="row">
<%= form_for [@year, @month, Comment.new] do |f| %>
<div class="form-group col-md-4 col-md-offset-4">
	<h4 style="margin-bottom: 30px;">New comment</h4>

	<label class="control-label">Priority: </label>
	
<%= f.select :status, ["Low", "Usual", "High"],{}, {class: "form-control ra-filtering-select-input ui-autocomplete-input", style: "display: inline-block;"} %>
    <label class="control-label">Content: </label>
    
	<%= f.text_area :content, class: "form-control", style: "margin-bottom: 30px;" %>
    
    
					<div class="form-group">
							<%= f.submit "Add comment", class: "btn btn-primary btn-lg btn-block login-button", id: "turbo", style: "background: #d84b6b; border: #d84b6b;" %> 
						</div>
    
</div>
<% end %>
</div>



<style>

.calendar-base {
  width: 700px;
  height: 500px;
  border-radius: 20px;
  background-color: white;
  margin-top: 10%;
  z-index: -1;
  color: black;
}

.month-color {
  color: #27AE60;
}
.month-hover:hover{
  color:#27e879 !important;
}

.months {
  color: #AAAAAA;
  margin-left: -60px; 
  word-spacing: 10px;
}

.month-line {
  margin-left: -60px; 	
  max-width: 800px;
  width: 500px;
  border-color: #E8E8E8;
}

.days {
  margin-left: -60px; 
  color: #AAAAAA;
  position: relative;
  font-size: 18px;
  word-spacing: 35px;
  font-weight: 600;
}

.num-dates {
  float: right;
  position: relative;
  right: 50px;
  z-index: 1;
}

.first-week {
  margin-bottom: 25px;
  word-spacing: 59px;
  width: 700px;
}

.second-week {
  margin-bottom: 25px;
  word-spacing: 59px;
}

.third-week {
  margin-bottom: 25px;
  word-spacing: 59px;
}

.fourth-week {
  margin-bottom: 25px;
  word-spacing: 59px;
}

.fifth-week {
  margin-bottom: 25px;
  word-spacing: 59px;
}

.sixth-week {
  margin-bottom: 25px;
  word-spacing: 59px;
}

.active-day {
  margin-right: -8px;	
  margin-left: -8px;	
  padding: 8px;	
  color: white;	
  width: 35px;
  height: 35px;
  border-radius: 50%;
  background-color: #2ECC71;
  display: inline-block;
}

.white {
  color: white;
}


.two {
  position: relative;

  left: 535px;
}

.grey {
  color: #AAAAB1;
}

.calendar-left {
  width: 300px;
  height: 500px;
  border-radius: 20px 0px 0px 20px;
  background-color: #2ECC71;
  z-index: -1;
  color: white;
}



.num-date {
  font-size: 100px;
  width: 50%;
  padding-left: 14%; 
  font-weight: 700;
}

.day {
  width: 50%;
  padding-left: 25%; 
  font-size: 70px;
  position: relative;
  bottom: 30px;
}

.month-day:hover:after {
  content: "add";	
  font-weight: bold;
  margin-top: -20px;
  margin-bottom: -20px;	
  margin-left: -24px;	
  margin-right: -11px;
  padding: 6px;	
  color: white;	
  width: 35px;
  height: 35px;
  border-radius: 50%;
  background-color: #2ECC71;
  display: inline-block;
}

.current-events {
  font-size: 15px;
  position: relative;
  margin-left: 25px;
  bottom: 30px;
}

.posts {
  text-decoration: underline dotted;
}
.posts:hover{
  color:#27e879 !important;
}


.event-line {
  width: 90%;
}

.add-event {
  width: 20px;
  height: 20px;
  padding: 0px;
  border-radius: 50%;
  border: solid white 2px;
  position: relative;
  bottom: 42px;
  left: 260px;
}

.add {
  font-size: 25px;
  position: relative;
  left: 1px;
  bottom: 10px;
}

.add:hover, .create-event:hover, .add-event:hover{
  color:#27e879 !important;
  border-color: #27e879 !important;
}
</style>