config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :users do 
    resources :years
  end
  resources :hospitals

  resources :years do
    resources :comments, module: :years
    resources :months do
    resources :comments, module: :months      
      resources :days do
        resources :comments, module: :days
        resources :sugar_levels
        resources :meals
        resources :exercises
        resources :warnings
        resources :insulin_injections
      end
    end
  end

  get "add_day", to: "days#add_day" 
  get "/users/add_patient/:id", to: "users#add_patient"
  get "/users/accept_request/:id", to: "users#accept_request"
  get "/users/add_to_hospital/:id", to: "hospitals#add_to_hospital"
  get "/users/accept_hospital/:id", to: "hospitals#accept_hospital"
  get "/users/deny_hospital", to: "hospitals#deny_hospital"
  get "/personal_page", to: "users#personal_page"
  get "/predict_bsl/day_:id", to: "days#predict_blood_sugar_level"

  root "years#index"
end

app/models/warning.rb
class Warning < ApplicationRecord
  belongs_to :day
  validates :begining, presence: true, timeliness: { type: :datetime }
  validates :ending, presence: true, timeliness: { type: :datetime }
  validates :reason, length: {minimum: 4, maximum: 50}, if: :reason_not_empty?
  validates :description, length: {minimum: 10, maximum: 2000}, if: :description_not_empty?

  def reason_not_empty?
  	!(reason.empty?)
  end

  def description_not_empty?
  	!(description.empty?)
  end

end

app/controllers/warnings_controller.rb
class WarninggsController < ApplicationController

  before_action :set_day, only: [:destroy]

  def create
    @day = Day.find(params[:day_id])
    @month = Month.find(@day.month_id)
    @year = Year.find(@month.year_id)
    @day.warninggs.create(warningg_params)
    last_warningg = @day.warninggs.last
    time_creation_begining = "#{@day.created_at.year}"+"-"+
      "#{@day.created_at.month}"+"-"+"#{@day.created_at.day} #{params[:warningg][:begining]}"
    time_creation_ending = "#{@day.created_at.year}"+"-"+
      "#{@day.created_at.month}"+"-"+"#{@day.created_at.day} #{params[:warningg][:ending]}"
    last_warningg.update(begining: time_creation_begining,
                         ending: time_creation_ending, created_at: time_creation_begining,
                         updated_at: time_creation_ending)
    scopes(@day)
    @warningg = @day.warninggs.last(2).first
    respond_to do |format|
      format.js
    end
  end

  def edit
    @warningg = Warningg.find(params[:id])
    @day = Day.find(@warningg.day_id)
    @month = Month.find(@day.month_id)
    @year = Year.find(@month.year_id)
    respond_to do |format|
      format.json { head :no_content }
      format.js
    end
  end

  def show

  end

  module Selectors
    def without_emty_slots
      select { |k, v| v != 0 }
    end
  end

  Hash.class_eval { include Selectors }

  def scopes(day)
    @s_l = day.sugar_levels.group_by_minute(:created_at).sum(:mmol)
    @result = @s_l.without_emty_slots
    @meals = day.meals.group_by_minute(:created_at).sum(4)
    @meals_result = @meals.without_emty_slots
    @insulin = day.exercises.group_by_minute(:created_at).sum(3)
    @insulin_result = @insulin.without_emty_slots
    @exercise_start = day.exercises.group_by_minute(:begining).sum(10)
    @exercise_end = day.exercises.group_by_minute(:ending).sum(10)
    @warningg_start = day.warninggs.group_by_minute(:begining).sum(15)
    @warningg_end = day.warninggs.group_by_minute(:ending).sum(15)
    @prediction = day.bsl_predictions.any? ? day.bsl_predictions.last.prediction.round(2) : 0
  end

  def update
    @warningg = Warningg.find(params[:id])
    @day = Day.find(@warningg.day_id)
    @month = Month.find(@day.month_id)
    @year = Year.find(@month.year_id)
    time_creation_begining = "#{@day.created_at.year}"+"-"+
      "#{@day.created_at.month}"+"-"+"#{@day.created_at.day} #{params[:warningg][:begining]}"
    time_creation_ending = "#{@day.created_at.year}"+"-"+
      "#{@day.created_at.month}"+"-"+"#{@day.created_at.day} #{params[:warningg][:ending]}"
    @warningg.update(begining: time_creation_begining,
                     ending: time_creation_ending, created_at: time_creation_begining,
                     updated_at: time_creation_ending, description: params[:warningg][:description],
                     reason: params[:warningg][:reason])
    scopes(@day)
    respond_to do |format|
      format.json
      format.js
    end
  end

  def destroy
    @day = Day.find(@warningg.day_id)
    @month = Month.find(@day.month_id)
    @year = Year.find(@month.year_id)
    @day.warninggs.delete @warningg
    scopes @day
    respond_to do |format|
      format.json { head :no_content }
      format.js
    end
  end

  private

  def set_day
    @day = Day.find(params[:day_id])
    @warningg = @day.warninggs.find(params[:id])
  end

  def warningg_params
    params.require(:warningg).permit(:reason, :description, :created_at, :day_id, :begining, :ending)
  end

end

app/helpers/warnings_helper.rb
module WarningsHelper

  def warnings(start_points, end_points, result, meals_result, insulin_result, exercise_start, exercise_end, prediction)

    data = []
    start_points.select! {|k, v| v != 0}
    start_points.to_a.each {|e| data << e}
    end_points.select! {|k, v| v != 0}
    areas = data.zip end_points.to_a
    area = []
    i = 0

    if areas != nil && areas.last != nil
      areas.last.pop if areas.last.last == nil
    end

    areas.each do |variable|
      i += 1
      area << {name: "Warning #{i}", data: variable, type: "area"}
    end

    ex_info = []
    exercise_start.select! {|k, v| v != 0}
    exercise_start.to_a.each {|e| ex_info << e}
    exercise_end.select! {|k, v| v != 0}
    intervals = ex_info.zip exercise_end.to_a
    interval = []
    j = 0

    if intervals != nil && intervals.last != nil
      intervals.last.pop if intervals.last.last == nil
    end

    intervals.each do |variable|
      j += 1
      area << {name: "Exercise #{j}", data: variable, type: "area"}
    end

    area << {name: "Blood sugar level", data: result }
    area << {name: "Meal time", data: meals_result, type: "scatter", label: "Value"}
    area << {name: "Insulin injections", data: insulin_result, type: "scatter"}
    if prediction != 0
      if result.any?
        area << {name: "Future blood sugar level", data: [result.to_a.last,[result.to_a.last.first + 2.hours, prediction]]}
      end
    end
    area
  end

end

app/views/warnings/_line_chart.html.erb
 <div id="lineChart">
<%= line_chart warnings(@warning_start, @warning_end, @result, @meals_result, @insulin_result, @exercise_start, @exercise_end, @prediction) %>
</div>

app/views/warnings/_pie_chart.html.erb
 <div id="pieChart">
<%= pie_chart((@day.sugar_levels.group(:status).count), adapter: "google") %>
</div>

app/views/warnings/_warning.html.erb
<table class="table table-hover" id="tableWarning">
  <thead class="black white-text">
    <tr>
      <th scope="col">Reason</th>
      <th scope="col">Description</th>
      <th scope="col">Begining</th>
      <th scope="col">Ending</th>
      <th scope="col">Edit</th>
      <th scope="col">Delete</th>
    </tr>
  </thead>
  <tbody>
<% @day.warnings.each do |warning| %>


<div class="modal fade" id="warningModal_<%= warning.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Warning description</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="<%=warning.id %>_description">
        <%= warning.description == nil ? "There is no description yet" : warning.description %>
      </div>
    </div>
  </div>
</div>


    <tr id="warning_<%=warning.id %>">
      <th scope="row" id="<%=warning.id %>_reason"><%= warning.reason %></th>
      <td><a href="#" data-toggle="modal" data-target="#warningModal_<%= warning.id %>">Read</a></td>
      <td id="<%=warning.id %>_begining"><%= warning.begining.to_datetime.strftime('%H:%M') %></td>
      <td id="<%=warning.id %>_ending"><%= warning.ending.to_datetime.strftime('%H:%M') %></td>
      <td><%= link_to "Edit", edit_year_month_day_warning_path(@year, @month, @day, warning), remote: true %></td>
      <td><%= link_to "Delete", year_month_day_warning_path(@year, @month, @day, warning), method: :delete, remote: true %></td>
    </tr>
<% end %>
  </tbody>
</table>

app/views/warnings/_warning_form.html.erb
    <%= form_for([@year, @month, @day, @warning], remote: true ) do |f| %>
    <div id="warning_<%= @warning.id %>">
      <p scope="row"><%= f.text_field :reason, class: "form-control", placeholder: "reason" %></p>
      <p><%= f.text_field :description, class: "form-control", placeholder: "description" %></p>
      <p><%= f.text_field :begining, class: "form-control", placeholder: "time", id: "#{@warning.id}_time", value: "#{@warning.begining.to_datetime.strftime('%H:%M')}" %></p>
      <p><%= f.text_field :ending, class: "form-control", placeholder: "time", id: "#{@warning.id}_time", value: "#{@warning.ending.to_datetime.strftime('%H:%M')}" %></p>      
      <p></p>
      <p><%= f.submit "Update", class: "btn btn-primary btn-lg btn-block login-button", style: "padding: 5px;" %></p>
    </div>
<% end %>

app/views/warnings/create.js.erb
$("#tableWarning").html("<%= j render 'warning' %>");
$('#reason').val('');
$('#warningdescription').val('');
$('#timeWarningBegining').val('');
$('#timeWarningEndning').val('');
$("#notifier").text("Warning is succsessfully created");
$("#lineChart").html('<%= j render "line_chart" %>');
$("#pieChart").html('<%= j render "pie_chart" %>');
window.location.href = '#lineChart'

app/views/warnings/destroy.js.erb
$("#warning_<%= @warning.id %>").fadeOut(500, function(){
	$(this).remove();
	$("#notifier").text("Warning is succsessfully deleted");
	$("#lineChart").html('<%= j render "line_chart" %>');
	$("#pieChart").html('<%= j render "pie_chart" %>');
	window.location.href = '#lineChart'
});

app/views/warnings/edit.js.erb
$("#herewarning").html('<%= j render "warning_form" %>');

app/views/warnings/update.js.erb
$("#<%= @warning.id %>_begining").text("<%= @warning.begining.to_datetime.strftime('%H:%M') %>");
$("#<%= @warning.id %>_ending").text("<%= @warning.ending.to_datetime.strftime('%H:%M') %>");
$("#<%= @warning.id %>_reason").text("<%= @warning.reason %>");
$("#<%= @warning.id %>_description").text("<%= @warning.description %>");
$("#lineChart").html('<%= j render "line_chart" %>');
$("#pieChart").html('<%= j render "pie_chart" %>');
window.location.href = '#lineChart'
$("#herewarning").remove();
$("#therewarning").append("<div id='herewarning'></div>");
$("#notifier").text("warning is succsessfully updated");