config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :users do 
    resources :years
  end
  resources :hospitals

  resources :years do
    resources :comments, module: :years
    resources :months do
    resources :comments, module: :months      
      resources :days do
        resources :comments, module: :days
        resources :sugar_levels
        resources :meals
        resources :exercises
        resources :warnings
        resources :insulin_injections
      end
    end
  end

  get "add_day", to: "days#add_day" 
  get "/users/add_patient/:id", to: "users#add_patient"
  get "/users/accept_request/:id", to: "users#accept_request"
  get "/users/add_to_hospital/:id", to: "hospitals#add_to_hospital"
  get "/users/accept_hospital/:id", to: "hospitals#accept_hospital"
  get "/users/deny_hospital", to: "hospitals#deny_hospital"
  get "/personal_page", to: "users#personal_page"
  get "/predict_bsl/day_:id", to: "days#predict_blood_sugar_level"

  root "years#index"
end

app/models/sugar_level.rb
class SugarLevel < ApplicationRecord
  belongs_to :day
  validate :which_day
  validates :created_at, presence: true, timeliness: { type: :datetime }
  validates :mmol, presence: true
  before_save :add_status

  scope :by_month, lambda { |month| where('extract(month from created_at) = ?', month) }
  scope :created_between, lambda {|start_date, end_date, day_id| where("created_at >= ? AND created_at <= ? AND day_id = ?", start_date, end_date, day_id )}

  def which_day
    unless day.created_at.day == created_at.day && day.created_at.month == created_at.month && day.created_at.year == created_at.year
      errors.add(:alert, "is not valid or is not active")
    end
  end

  def add_status
    if mmol < 3.7
      self[:status] = "Low"
    elsif mmol > 8.0
      self[:status] = "High"
    else
      self[:status] = "Normal"
    end
  end

end

app/controllers/sugar_levels_controller.rb
class SugarLevelsController < ApplicationController

  before_action :set_day, only: [:destroy]

  def edit
    @sugar_level = SugarLevel.find(params[:id])
    @day = Day.find(@sugar_level.day_id)
    @month = Month.find(@day.month_id)
    @year = Year.find(@month.year_id)
    respond_to do |format|
      format.json { head :no_content }
      format.js
    end
  end

  def show

  end

  def scopes(day)
    @s_l = day.sugar_levels.group_by_minute(:created_at).sum(:mmol)
    @result = @s_l.without_emty_slots
    @meals = day.meals.group_by_minute(:created_at).sum(4)
    @meals_result = @meals.without_emty_slots
    @insulin = day.insulin_injections.group_by_minute(:created_at).sum(3)
    @insulin_result = @insulin.without_emty_slots
    @exercise_start = day.exercises.group_by_minute(:begining).sum(10)
    @exercise_end = day.exercises.group_by_minute(:ending).sum(10)
    @warning_start = day.warninggs.group_by_minute(:begining).sum(15)
    @warning_end = day.warninggs.group_by_minute(:ending).sum(15)
    @prediction = day.bsl_predictions.any? ? day.bsl_predictions.last.prediction.round(2) : 0
  end

  def update
    @sugar_level = SugarLevel.find(params[:id])
    @day = Day.find(@sugar_level.day_id)
    @month = Month.find(@day.month_id)
    @year = Year.find(@month.year_id)
    @time_creation = "#{@day.created_at.year}"+"-"+
      "#{@day.created_at.month}"+"-"+"#{@day.created_at.day} #{params[:sugar_level][:created_at]}"
    @sugar_level.update mmol: params[:sugar_level][:mmol]
    @sugar_level.update created_at: @time_creation
    scopes(@day)
    respond_to do |format|
      format.json
      format.js
    end
  end

  def destroy
    @day = Day.find(@sugar_level.day_id)
    @month = Month.find(@day.month_id)
    @year = Year.find(@month.year_id)
    @day.sugar_levels.delete @sugar_level
    scopes @day
    respond_to do |format|
      format.json { head :no_content }
      format.js
    end
  end

  def create
    @day = Day.find(params[:day_id])
    @month = Month.find(@day.month_id)
    @year = Year.find(@month.year_id)
    @time_creation = "#{@day.created_at.year}"+"-"+
      "#{@day.created_at.month}"+"-"+"#{@day.created_at.day} #{params[:sugar_level][:created_at]}"
    @day.sugar_levels.create(sugar_level_params)
    @day.sugar_levels.last.update(created_at: @time_creation)
    scopes(@day)
    @sugar_level = @day.sugar_levels.last(2).first
    respond_to do |format|
      format.json { head :no_content }
      format.js
    end
  end

  private

  def set_day
    @day = Day.find(params[:day_id])
    @sugar_level = @day.sugar_levels.find(params[:id])
  end

  def sugar_level_params
    params.require(:sugar_level).permit(:mmol, :status, :day_id, :created_at, :id)
  end
end

app/views/sugar_levels/_sugar_level.html.erb
<table class="table table-hover" id="table">
  <thead class="black white-text">
    <tr>
      <th scope="col">mmol</th>
      <th scope="col">Time</th>
      <th scope="col">Edit</th>
      <th scope="col">Delete</th>
    </tr>
  </thead>
  <tbody>
<% @day.sugar_levels.each do |sugar_level| %>  	
    <tr id="sugar_level_<%= sugar_level.id %>">
      <th scope="row" id="<%=sugar_level.id %>_mmol"><%= sugar_level.mmol %></th>
      <td id="<%=sugar_level.id %>_created_at"><%= sugar_level.created_at.strftime('%H:%M') %></td>
      <td><%= link_to "Edit", edit_year_month_day_sugar_level_path(@year, @month, @day, sugar_level), remote: true %></td>
      <td><%= link_to "Delete", year_month_day_sugar_level_path(@year, @month, @day, sugar_level), method: :delete, remote: true %></td>
    </tr>
<% end %>
  </tbody>
</table>

app/views/sugar_levels/_sugar_level_form.html.erb
    <%= form_for([@year, @month, @day, @sugar_level], remote: true ) do |f| %>
    <div id="sugar_level_<%= @sugar_level.id %>">
      <p scope="row"><%= f.text_field :mmol, class: "form-control", placeholder: "mmol" %></p>
      <p><%= f.text_field :created_at, class: "form-control", placeholder: "time", id: "#{@sugar_level.id}_time", value: "#{@sugar_level.created_at.strftime('%H:%M')}" %></p>
      <p></p>
      <p><%= f.submit "Update", class: "btn btn-primary btn-lg btn-block login-button", style: "padding: 5px;" %></p>
    </div>
<% end %>

app/views/sugar_levels/create.js.erb
 $("#tableSugarLevel").html("<%= j render 'sugar_level' %>");
 $('#mmol').val('');
 $('#timemmol').val('');
 $("#sugar_levels_notify").text("Sugar level is succsessfully created");
 $("#lineChart").html('<%= j render "line_chart" %>');
 $("#pieChart").html('<%= j render "pie_chart" %>');
 window.location.href = '#lineChart'

app/views/sugar_levels/destroy.js.erb
$("#sugar_level_<%= @sugar_level.id %>").fadeOut(500, function(){
	$(this).remove();
	$("#sugar_levels_notify").text("Sugar level is succsessfully deleted");
	$("#lineChart").html('<%= j render "line_chart" %>');
	$("#pieChart").html('<%= j render "pie_chart" %>');
	window.location.href = '#lineChart'
});

app/views/sugar_levels/edit.js.erb
$("#here").html('<%= j render "sugar_level_form" %>');

app/views/sugar_levels/update.js.erb
$("#<%= @sugar_level.id %>_created_at").text("<%= @sugar_level.created_at.strftime('%H:%M') %>");
$("#<%= @sugar_level.id %>_mmol").text("<%= @sugar_level.mmol %>");
$("#lineChart").html('<%= j render "line_chart" %>');
$("#pieChart").html('<%= j render "pie_chart" %>');
window.location.href = '#lineChart'
$("#here").remove();
$("#there").append("<div id='here'></div>");