config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :users do 
    resources :years
  end
  resources :hospitals

  resources :years do
    resources :comments, module: :years
    resources :months do
    resources :comments, module: :months      
      resources :days do
        resources :comments, module: :days
        resources :sugar_levels
        resources :meals
        resources :exercises
        resources :warnings
        resources :insulin_injections
      end
    end
  end

  get "add_day", to: "days#add_day" 
  get "/users/add_patient/:id", to: "users#add_patient"
  get "/users/accept_request/:id", to: "users#accept_request"
  get "/users/add_to_hospital/:id", to: "hospitals#add_to_hospital"
  get "/users/accept_hospital/:id", to: "hospitals#accept_hospital"
  get "/users/deny_hospital", to: "hospitals#deny_hospital"
  get "/personal_page", to: "users#personal_page"
  get "/predict_bsl/day_:id", to: "days#predict_blood_sugar_level"

  root "years#index"
end

app/models/year.rb
class Year < ApplicationRecord
  belongs_to :user
  has_many :months, dependent: :destroy
  has_many :comments, as: :commentable  
  before_save :change_created_at
  validates_uniqueness_of :year_number, scope: :id

  def change_created_at
    self[:created_at] = "#{self.year_number}-01-01"
  end

end

app/controllers/years/comments_controller.rb
class Years::CommentsController < CommentsController
  before_action :set_commentable

  private

  def set_commentable
  	@commentable = Year.find(params[:year_id])
  end

end

app/controllers/years_controller.rb
class YearsController < ApplicationController

  def create
    @user = current_user
    if Year.all.select{|year| year.year_number == year_params[:year_number].to_i }.empty?
      current_user.years.create(year_params)
    else
      flash[:notice] = "Year already exists"
    end
    redirect_to :root
  end

  def destroy
    @year = Year.find(params[:id])
    @year.destroy
    redirect_to :root
  end

  def show
    @year = Year.find(params[:id])
    @total = []
    all_user_mmols = []
    all_user_times = []
    @year.months.each do |month|
      month.days.each do |day|
        all_user_mmols << day.sugar_levels.map {|e| e.mmol}
        all_user_times << day.sugar_levels.map {|e| e.created_at}
      end
      @total << {name: "#{month.month_name}", data: all_user_times.flatten.zip(all_user_mmols.flatten).to_h, type: "area"}
      all_user_mmols = []
      all_user_times = []
    end

    @status_hash = {}
    @sug = @year.months.map{|month| month.days.map{|day| day.sugar_levels.map{|sl| sl.status} }}
    @status_hash[:Low] = @sug.flatten.count("High")
    @status_hash[:High] = @sug.flatten.count("Low")
    @status_hash[:Normal] = @sug.flatten.count("Normal")
    @month_names = Date::MONTHNAMES[1..-1] - @year.months.map(&:month_name)
  end

  module Selectors
    def without_emty_slots
      select { |k, v| v != 0 }
    end
  end

  Hash.class_eval { include Selectors }

  def scopes
    @random_day_sample = Day.order("RANDOM()").includes(:bsl_predictions).where.not(bsl_predictions: {prediction: nil}).first
    @years = Year.all
    @year_collection = (1990..Time.now.year).to_a - Year.all.map(&:year_number)
    @s_l = @random_day_sample.sugar_levels.group_by_minute(:created_at).sum(:mmol)
    @result = @s_l.without_emty_slots
    @meals = @random_day_sample.meals.group_by_minute(:created_at).sum(4)
    @meals_result = @meals.without_emty_slots
    @insulin = @random_day_sample.insulin_injections.group_by_minute(:created_at).sum(3)
    @insulin_result = @insulin.without_emty_slots
    @exercise_start = @random_day_sample.exercises.group_by_minute(:begining).sum(10)
    @exercise_end = @random_day_sample.exercises.group_by_minute(:ending).sum(10)
    @warning_start = @random_day_sample.warninggs.where("reason = ?", "start").group_by_minute(:created_at).sum(15)
    @warning_end = @random_day_sample.warninggs.where("reason = ?", "end").group_by_minute(:created_at).sum(15)
    @prediction = @random_day_sample.bsl_predictions.any? ? @random_day_sample.bsl_predictions.last.prediction.round(2) : 0
  end

  def index
    scopes
    @status_hash = {}
    if user_signed_in?
      current_user.years.each do |year|
        year.months.each do |month|
          month.days.each do |day|
            sug = day.sugar_levels.map { |sl| sl.status }
            if @status_hash.empty?
              @status_hash[:Low] = sug.flatten.count("Low")
              @status_hash[:High] = sug.flatten.count("High")
              @status_hash[:Normal] = sug.flatten.count("Normal")
            else
              @status_hash[:Low] += sug.flatten.count("Low")
              @status_hash[:High] += sug.flatten.count("High")
              @status_hash[:Normal] += sug.flatten.count("Normal")
            end
          end
        end
      end
    end
    @total = []
    all_user_mmols = []
    all_user_times = []
    if user_signed_in?
      current_user.years.each do |year|
        year.months.each do |month|
          month.days.each do |day|
            all_user_mmols << day.sugar_levels.map {|e| e.mmol}
            all_user_times << day.sugar_levels.map {|e| e.created_at}
          end
        end
        @total << {name: "#{year.year_number}", data: all_user_times.flatten.zip(all_user_mmols.flatten).to_h, type: "area"}
        all_user_mmols = []
        all_user_times = []
      end
    end
    @users = User.where(role: "patient").page params[:page]
  end

  private

  def year_params
    params.require(:year).permit(:description, :year_number, :user_id)
  end

end

app/helpers/years_helper.rb
module YearsHelper
end

app/views/years/index.html.erb
<% if user_signed_in? %>

<% if current_user.role == "doctor" %>

<h2>Monitoring users:</h2>
<% current_user.pending_friends.each do |friend| %>
<div style="margin-top: 5%;">
<hr/>    
<h3>Full name: <%= link_to "#{friend.full_name}", "/users/#{friend.id}/years" %></h3>
<p>Current hospital: <%= friend.current_hospital %></p>
</div>
<% end %>

<% unless params[:user_id].nil? %>
<% if User.find(params[:user_id]).years.any? %>
<div class="row">	
<div class="list-group col-md-4 col-md-offset-4">
<h3>Years:</h3>	
<% User.find(params[:user_id]).years.each do |year| %>
<% unless year.nil? %>
<%= link_to "#{year.year_number}", "years/#{year.id}", class: "list-group-item list-group-item-action #{'active' if year.year_number == Time.now.year}" %>
<% end %>
<% end %>
</div>
</div>
<% end %>
<% end %>

<%= paginate @users %>

<% else %>

<%= line_chart @total %>
<%= pie_chart @status_hash %>

<div class="row">
<div class="col-md-4 col-md-offset-4">	
<%= simple_form_for current_user.years.new do |f| %>
<div class="form-group">
<%= f.input :year_number, collection: @year_collection %>
<%= f.hidden_field :user_id, value: current_user.id %>
</div>
<div class="form-group">
<%= f.submit "Add year", class: "btn btn-primary" %>
</div>
<% end %>
</div>
</div>

<% if current_user.years.any? %>
<div class="row">	
<div class="list-group col-md-4 col-md-offset-4">
<h3>Years:</h3>	
<% current_user.years.each do |year| %>
<% unless year.nil? %>
<%= link_to "#{year.year_number}", "years/#{year.id}", class: "list-group-item list-group-item-action #{'active' if year.year_number == Time.now.year}" %>
<% end %>
<% end %>
</div>
</div>
<% end %>

<% end %>

<% else %>


<h3 class="text-center" style="color: #36820a; margin-bottom: 5%;">
<%= t 'greetings_page.welcome' %>
</h3>
<%= line_chart warnings(@warning_start, @warning_end, @result, @meals_result, @insulin_result, @exercise_start, @exercise_end, @prediction) %>

<%= pie_chart((@random_day_sample.sugar_levels.group(:status).count), adapter: "google") %>


<% end %>

app/views/years/show.html.erb
<%= link_to "To main page", root_path %>
<div class="row">
	<div class="col-md-4 col-md-offset-4">
<%= simple_form_for([@year, @year.months.build], method: :post ) do |f| %>
<%= f.input :month_name, collection: @month_names %>
					<div class="form-group">
							<%= f.submit "Add month", class: "btn btn-primary btn-lg btn-block login-button" %> 
						</div>
<% end %>
</div>
</div>
<%= area_chart @total %>
<h3>
*Average result per month	
</h3>

<%= pie_chart @status_hash, adapter: "google"%>


    <%= button_to "Delete year", year_path(@year), class: "btn btn-primary btn-lg btn-block login-button", style: "width: 200px;", method: :delete, data: { confirm: "Are you sure?" } %>


<div class="row" style="margin-top: 5%;">
	<div class="col-md-4 col-md-offset-4">
<div class="list-group">
<h3>Months:	</h3>
<% @year.months.each do |month| %>
<% if month.id != nil%>
<%= link_to "#{month.month_name}", year_month_path(@year, month.id), class: "list-group-item list-group-item-action text-center" %>
<% end %>
<% end %>
</div>
</div>
</div>

<%= render partial: "comments/comments", locals: {commentable: @year} %>

<div class="row">
<%= form_for [@year, Comment.new] do |f| %>
<div class="form-group col-md-4 col-md-offset-4">
	<h4 style="margin-bottom: 30px;">New comment</h4>

	<label class="control-label">Priority: </label>
	
<%= f.select :status, ["Low", "Usual", "High"],{}, {class: "form-control ra-filtering-select-input ui-autocomplete-input", style: "display: inline-block;"} %>
    <label class="control-label">Content: </label>
    
	<%= f.text_area :content, class: "form-control", style: "margin-bottom: 30px;" %>
    
    
					<div class="form-group">
							<%= f.submit "Add comment", class: "btn btn-primary btn-lg btn-block login-button", id: "turbo", style: "background: #d84b6b; border: #d84b6b;" %> 
						</div>
    
</div>
<% end %>
</div>